[package]
name = "DirMap"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["open-source-core"]
resolver = "3"

[dependencies]
crossterm = "0.25"
ratatui = "0.30.2"
image = { version = "0.25", default-features = false, features = ["png"] }
ratatui-image = { version = "11.1", default-features = false, features = ["crossterm"] }
open-source-core = { path = "open-source-core" }

[build-dependencies]
winres = "0.1.12"
